import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { signIn, signOut, useSession } from "next-auth/client";

export default function Home() {
    const [session] = useSession();

    return (
        <div className={styles.container}>
            <Head>
                <title>WrapX</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main style={{ textAlign: "center" }}>
                Future Page of WrapX maybe.
                <br />
                <br />
                If you came from the discord server, you probably want to go{" "}
                <button
                    onClick={() => (session ? signOut() : signIn("discord"))}
                    style={{
                        border: "none",
                        backgroundColor: "transparent",
                        font: "unset",
                        margin: 0,
                        padding: 0,
                        color: "blue",
                        textDecoration: "underline",
                        cursor: "pointer",
                    }}
                >
                    Here
                </button>
                .
            </main>
        </div>
    );
}
